### ISSUE TITLE
azure/bootstrap: Name and place "management" subscription into hierarchy

### ISSUE THREAD

**Issue by JohannesRudolph** [meshcloud/collie-hub#108]
Similar to #97, though I'm not sure which module should handle this (maybe organization-hierarchy). Any preferences here @florianow ?

**Comment by florianow** [comment]
yes true, the subscription will be first used for logging but feels not well chosen.

**Comment by florianow** [comment]
I would rename the subscription to something more security related because it holds stuff like LAW, Sentinel and Automation However, I would moving it the OH kit. 

[Azure Enterprise Scale Docu](https://github.com/Azure/Enterprise-Scale/wiki/How-Enterprise-Scale-Works#enterprise-scale-management-group-structure)
_Management: This Management Group contains the dedicated subscription for management, monitoring, and security, which will host Azure Log Analytics, Azure Automation, and Azure Sentinel. Specific Azure policies are assigned to harden and manage the resources in the management subscription._
